type Field =
  | 'alias'
  | 'arid'
  | 'artist'
  | 'artistname'
  | 'asin'
  | 'barcode'
  | 'catno'
  | 'comment'
  | 'country'
  | 'creditname'
  | 'date'
  | 'discids'
  | 'discidsmedium'
  | 'format'
  | 'label'
  | 'laid'
  | 'lang'
  | 'mediums'
  | 'packaging'
  | 'primarytype'
  | 'quality'
  | 'reid'
  | 'release'
  | 'releaseaccent'
  | 'rgid'
  | 'script'
  | 'secondarytype'
  | 'status'
  | 'tag'
  | 'tracks'
  | 'tracksmedium'
  | 'type'

export type ReleaseSearchFields = Partial<Record<Field, string>>
